### ISSUE TITLE
Add callback before dispatch 

### ISSUE THREAD

**Issue by lpotherat** [dannyvankooten/PHP-Router#115]
As an enhancement, it could be useful to have a "shouldDispatchCallback".

- Router class have a setShouldDispatchCallback method
- Just before the call to $routes->dispatch(), the router calls the callback, if callback return false, route is ignored, else the callback returns the route.

=> it can be used to allow / disallow access to routes

**Comment by antoine-pous** [comment]
I don't understand why this feature should be managed by PHPRouter.

If you want ignore some routes in some cases you can do it by managing them with multiple files like `web.routes.php`, `api.routes.php`, `webmin.route.php` etc...

Instead of loading directly all routes you test your requirements and load only what you need. This is the best way to avoid any risk of unwanted access to routes.

**Comment by lpotherat** [comment]
Maybe the solution above is not the best, my need at first is to allow/disallow a route at runtime  in a restricted environnement

1. User logs in
2. ACL management is loaded
3. Before dispatching route, ACL are checked (via callback), and we can decide to re-route user to error page or login page.

**Comment by antoine-pous** [comment]
The goal of PHPRouter is routing, not providing a middleware interface.

On all project i had built with PHPRouter i use dynamic load form files, so guest can't access to restricted area, user can't get access to ACP etc...

Currently the demo is not available due to major changes in progress to made PHPRouter stable.

1. Check user status (Guest, Registered, Admin)
2. Load routes availables related to the user Group an personnal permissions
3. Serve the client with the content or error 404

If user need to be granted to get access for a ressource the controller manage it and display the right view with custom message.

**Comment by lpotherat** [comment]
Ok I understand, I wanted to avoid the acl check call in each methods called by the router.  
I'll have to find another solution, thanks by the way.

**Comment by antoine-pous** [comment]
If you wont user ACL management in your controller you can do it into your routes files and change the controller called in your route.
